spring.application.name=saas

# Database Configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
spring.liquibase.enabled=true

spring.web.error.include-stacktrace=never

# JWT Configuration
app.jwt.secret=
app.jwt.expiration=

# Password reset JWT
app.jwt.reset-password.secret=
app.jwt.reset-password.expiration=

spring.docker.compose.file=compose.yml

# Social authentication
app.social-authentication.google.client-id=
app.social-authentication.google.client-secret=
app.social-authentication.google.scope=openid email
app.social-authentication.google.redirect-uri=http://localhost:8080/api/social-authentication/google/callback
app.social-authentication.google.response-type=code
app.social-authentication.google.grant-type=authorization_code
app.social-authentication.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
app.social-authentication.google.token-uri=https://oauth2.googleapis.com/token
app.social-authentication.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo