spring.application.name=saas

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
spring.liquibase.enabled=true

spring.web.error.include-stacktrace=never

# JWT Configuration
app.jwt.authentication-token.secret=${JWT_AUTHENTICATION_TOKEN_SECRET:dev-only-authentication-token-secret-change-me-0123456789}
app.jwt.authentication-token.expiration=${JWT_AUTHENTICATION_TOKEN_EXPIRATION:300}
app.jwt.refresh-token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION:3600}
app.jwt.reset-password-token.secret=${JWT_RESET_PASSWORD_TOKEN_SECRET:dev-only-reset-password-token-secret-change-me-0123456789}
app.jwt.reset-password-token.expiration=${JWT_RESET_PASSWORD_TOKEN_EXPIRATION:300}

spring.docker.compose.file=compose.yml

# Social authentication
app.social-authentication.google.client-id=${GOOGLE_CLIENT_ID:google-client-id}
app.social-authentication.google.client-secret=${GOOGLE_SECRET:google-client-secret}
app.social-authentication.google.scope=openid email
app.social-authentication.google.redirect-uri=http://localhost:8080/api/v1/public/social-authentication/callback/google
app.social-authentication.google.response-type=code
app.social-authentication.google.grant-type=authorization_code
app.social-authentication.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
app.social-authentication.google.token-uri=https://oauth2.googleapis.com/token
app.social-authentication.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo