spring.liquibase.contexts=local


# Override

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# JWT Configuration
app.jwt.secret=secret-secret-secret-secret-secret-secret-secret-secret-secret-secret-secret
app.jwt.expiration=3600

# Password reset JWT
app.jwt.reset-password.secret=secret-secret-secret-secret-secret-secret-secret-secret-secret-secret-secret
app.jwt.reset-password.expiration=3600

# OAuth2
app.social-authentication.google.client-id=823964255639-89uiioir8u1nmmncb7ngjv17t138b2hp.apps.googleusercontent.com
app.social-authentication.google.client-secret=