spring.liquibase.contexts=local


# Override

# Database Configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# JWT Configuration
app.jwt.secret=
app.jwt.expiration=

# Password reset JWT
app.jwt.reset-password.secret=
app.jwt.reset-password.expiration=